from reportlab.lib.styles import ParagraphStyle


def get_bullet_style(styles):
    '''Bullet points'''
    return ParagraphStyle('bullet_style',
                          fontName="Helvetica",
                          alignment=0,
                          allowOrphans=0,
                          allowWidows=0,
                          borderColor=None,
                          borderPadding=0,
                          borderRadius=None,
                          borderWidth=100,
                          bulletAnchor='start',
                          bulletFontName='Helvetica',
                          bulletFontSize=10,
                          bulletIndent=-10,
                          embeddedHyphenation=0,
                          endDots=None,
                          firstLineIndent=0,
                          fontSize=10,
                          justifyBreaks=0,
                          justifyLastLine=0,
                          leading=12,
                          leftIndent=0,
                          linkUnderline=0,
                          rightIndent=20,
                          spaceAfter=0,
                          spaceBefore=0,
                          spaceShrinkage=0.05,
                          splitLongWords=1,
                          strikeGap=1,
                          strikeOffset=0.25,
                          strikeWidth=1,
                          textTransform=None,
                          underlineGap=1,
                          underlineOffset=-0.125,
                          underlineWidth=1,
                          uriWasteReduce=0,
                          wordWrap=None,
                          )


def get_fluff_style(styles):
    '''Footer fluff text'''
    return ParagraphStyle('fluff_style',
                          fontName="Helvetica",
                          alignment=0,
                          allowOrphans=0,
                          allowWidows=0,
                          borderColor=None,
                          borderPadding=0,
                          borderRadius=None,
                          borderWidth=100,
                          embeddedHyphenation=0,
                          endDots=None,
                          firstLineIndent=0,
                          fontSize=10,
                          justifyBreaks=0,
                          justifyLastLine=0,
                          leading=12,
                          leftIndent=0,
                          linkUnderline=0,
                          rightIndent=20,
                          spaceAfter=0,
                          spaceBefore=0,
                          spaceShrinkage=0.05,
                          splitLongWords=1,
                          strikeGap=1,
                          strikeOffset=0.25,
                          strikeWidth=1,
                          textTransform=None,
                          underlineGap=1,
                          underlineOffset=-0.125,
                          underlineWidth=1,
                          uriWasteReduce=0,
                          wordWrap=None,
                          )


def get_header_style(styles):
    '''Section heading'''
    return ParagraphStyle('header_style',
                          fontName="Helvetica",
                          alignment=2,
                          allowOrphans=0,
                          allowWidows=0,
                          borderColor=None,
                          borderPadding=0,
                          borderRadius=None,
                          borderWidth=100,
                          bulletAnchor='start',
                          bulletFontName='Helvetica',
                          bulletFontSize=10,
                          bulletIndent=-10,
                          embeddedHyphenation=0,
                          endDots=None,
                          firstLineIndent=0,
                          fontSize=12,
                          justifyBreaks=0,
                          justifyLastLine=0,
                          leading=12,
                          leftIndent=0,
                          linkUnderline=0,
                          rightIndent=20,
                          spaceAfter=0,
                          spaceBefore=0,
                          spaceShrinkage=0.05,
                          splitLongWords=1,
                          strikeGap=1,
                          strikeOffset=0.25,
                          strikeWidth=1,
                          textTransform=None,
                          underlineGap=1,
                          underlineOffset=-0.125,
                          underlineWidth=1,
                          uriWasteReduce=0,
                          wordWrap=None,
                          )
